/******************************************************************************
 * C64 Emulator -- for the web                                                *
 * (c) 2022-2023 by Andreas Schwenk, License: GPLv3                           *
 * mailto:contact@compiler-construction.com                                   *
 *****************************************************************************/

export const mnemonics: string[] = [
    'BRK Force Break',
    'ORA OR Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'ORA OR Memory with Accumulator',
    'ASL Shift Left One Bit',
    'XXX ILLEGAL',
    'PHP Push Processor Status on Stack',
    'ORA OR Memory with Accumulator',
    'ASL Shift Left One Bit',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'ORA OR Memory with Accumulator',
    'ASL Shift Left One Bit',
    'XXX ILLEGAL',
    'BPL Branch on Result Plus',
    'ORA OR Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'ORA OR Memory with Accumulator',
    'ASL Shift Left One Bit',
    'XXX ILLEGAL',
    'CLC Clear Carry Flag',
    'ORA OR Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'ORA OR Memory with Accumulator',
    'ASL Shift Left One Bit',
    'XXX ILLEGAL',
    'JSR Jump to New Location Saving Return Address',
    'AND AND Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'BIT Test Bits in Memory with Accumulator',
    'AND AND Memory with Accumulator',
    'ROL Rotate One Bit Left',
    'XXX ILLEGAL',
    'PLP Pull Processor Status from Stack',
    'AND AND Memory with Accumulator',
    'ROL Rotate One Bit Left',
    'XXX ILLEGAL',
    'BIT Test Bits in Memory with Accumulator',
    'AND AND Memory with Accumulator',
    'ROL Rotate One Bit Left',
    'XXX ILLEGAL',
    'BMI Branch on Result Minus',
    'AND AND Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'AND AND Memory with Accumulator',
    'ROL Rotate One Bit Left',
    'XXX ILLEGAL',
    'SEC Set Carry Flag',
    'AND AND Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'ORA OR Memory with Accumulator',
    'ASL Shift Left One Bit',
    'XXX ILLEGAL',
    'RTI Return from Interrupt',
    'EOR Exclusive-OR Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'EOR Exclusive-OR Memory with Accumulator',
    'LSR Shift One Bit Right',
    'XXX ILLEGAL',
    'PHA Push Accumulator on Stack',
    'EOR Exclusive-OR Memory with Accumulator',
    'LSR Shift One Bit Right',
    'XXX ILLEGAL',
    'JMP Jump to new Location',
    'EOR Exclusive-OR Memory with Accumulator',
    'LSR Shift One Bit Right',
    'XXX ILLEGAL',
    'BVC Branch on Overflow Clear',
    'EOR Exclusive-OR Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'EOR Exclusive-OR Memory with Accumulator',
    'LSR Shift One Bit Right',
    'XXX ILLEGAL',
    'CLI Clear Interrupt Disable Bit',
    'EOR Exclusive-OR Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'EOR Exclusive-OR Memory with Accumulator',
    'LSR Shift One Bit Right',
    'XXX ILLEGAL',
    'RTS Return from Subroutine',
    'ADC Add Memory to Accumulator with Carry',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'ADC Add Memory to Accumulator with Carry',
    'ROR Rotate One Bit Right',
    'XXX ILLEGAL',
    'PLA Pull Accumulator from Stack',
    'ADC Add Memory to Accumulator with Carry',
    'ROR Rotate One Bit Right',
    'XXX ILLEGAL',
    'JMP Jump to new Location',
    'ADC Add Memory to Accumulator with Carry',
    'ROR Rotate One Bit Right',
    'XXX ILLEGAL',
    'BCS Branch on Carry Set',
    'ADC Add Memory to Accumulator with Carry',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'ADC Add Memory to Accumulator with Carry',
    'ROR Rotate One Bit Right',
    'XXX ILLEGAL',
    'SEI Set Interrupt Disable Status',
    'ADC Add Memory to Accumulator with Carry',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'ADC Add Memory to Accumulator with Carry',
    'ROR Rotate One Bit Right',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'STA Store Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'STY Store Index Y in Memory',
    'STA Store Accumulator',
    'STX Store Index X in Memory',
    'XXX ILLEGAL',
    'DEY Decrement Index Y by One',
    'XXX ILLEGAL',
    'TXA Transfer Index X to Accumulator',
    'XXX ILLEGAL',
    'STY Store Index Y in Memory',
    'STA Store Accumulator',
    'STX Store Index X in Memory',
    'XXX ILLEGAL',
    'BCC Branch on Carry Clear',
    'STA Store Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'STY Store Index Y in Memory',
    'STA Store Accumulator',
    'STX Store Index X in Memory',
    'XXX ILLEGAL',
    'TYA Transfer Index Y to Accumulator',
    'STA Store Accumulator',
    'TXS Transfer Index X to Stack Pointer',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'STA Store Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'LDY Load Index Y',
    'LDA Load Accumulator',
    'LDX Load Index X',
    'XXX ILLEGAL',
    'LDY Load Index Y',
    'LDA Load Accumulator',
    'LDX Load Index X',
    'XXX ILLEGAL',
    'TAY Transfer Accumulator to Index Y',
    'LDA Load Accumulator',
    'TAX Transfer Accumulator to Index X',
    'XXX ILLEGAL',
    'LDY Load Index Y',
    'LDA Load Accumulator',
    'LDX Load Index X',
    'XXX ILLEGAL',
    'BCS Branch on Carry Set',
    'LDA Load Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'LDY Load Index Y',
    'LDA Load Accumulator',
    'LDX Load Index X',
    'XXX ILLEGAL',
    'CLV Clear Overflow Flag',
    'LDA Load Accumulator',
    'TSX Transfer Stack Pointer to Index X',
    'XXX ILLEGAL',
    'LDY Load Index Y',
    'LDA Load Accumulator',
    'LDX Load Index X',
    'XXX ILLEGAL',
    'CPY Compare Memory and Index Y',
    'CMP Compare Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'CPY Compare Memory and Index Y',
    'CMP Compare Memory with Accumulator',
    'DEC Decrement Memory by One',
    'XXX ILLEGAL',
    'INY Increment Index Y by One',
    'CMP Compare Memory with Accumulator',
    'DEX Decrement Index X by One',
    'XXX ILLEGAL',
    'CPY Compare Memory and Index Y',
    'CMP Compare Memory with Accumulator',
    'DEC Decrement Memory by One',
    'XXX ILLEGAL',
    'BNE Branch on Result not Zero',
    'CMP Compare Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'CMP Compare Memory with Accumulator',
    'DEC Decrement Memory by One',
    'XXX ILLEGAL',
    'CLD Clear Decimal Mode',
    'CMP Compare Memory with Accumulator',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'CMP Compare Memory with Accumulator',
    'DEC Decrement Memory by One',
    'XXX ILLEGAL',
    'CPX Compare Memory and Index X',
    'SBC Subtract Memory from Accumulator with Borrow',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'CPX Compare Memory and Index X',
    'SBC Subtract Memory from Accumulator with Borrow',
    'INC Increment Memory by One',
    'XXX ILLEGAL',
    'INX Increment Index X by One',
    'SBC Subtract Memory from Accumulator with Borrow',
    'NOP No Operation',
    'SBC Subtract Memory from Accumulator with Borrow',
    'CPX Compare Memory and Index X',
    'SBC Subtract Memory from Accumulator with Borrow',
    'INC Increment Memory by One',
    'XXX ILLEGAL',
    'BEQ Branch on Result Zero',
    'SBC Subtract Memory from Accumulator with Borrow',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'SBC Subtract Memory from Accumulator with Borrow',
    'INC Increment Memory by One',
    'XXX ILLEGAL',
    'SED Set Decimal Flag',
    'SBC Subtract Memory from Accumulator with Borrow',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'XXX ILLEGAL',
    'SBC Subtract Memory from Accumulator with Borrow',
    'INC Increment Memory by One',
    'XXX ILLEGAL',
];
